name: merge-schedule
on:
  pull_request:
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          time_zone: Asia/Tokyo
          require_statuses_success: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
